services:
  - type: web
    name: whisper-api
    env: node
    plan: free
    buildCommand: npm install
    buildScript: |
      apt-get update
      apt-get install -y ffmpeg
    startCommand: node api/whisper.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
